org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Fabric Properties
  # check these on https://fabricmc.net/develop
  minecraft_version=26.2
  loader_version=0.19.3
  fabric_version=0.152.2+26.2

# Mod Properties
  group=com.minelittlepony
  displayname=Mson
  authors=Sollace
  description=Json-based entity models. Mson.

# Publishing
  minecraft_version_range=>=26.2 <26.3
  modrinth_loader_type=fabric
  modrinth_project_id=POWgsZW2

# Dependencies
  modmenu_version=20.0.0-beta.3
