org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Fabric Properties
  # check these on https://fabricmc.net/develop
  minecraft_version=1.21.10
  yarn_mappings=1.21.10+build.2
  loader_version=0.17.3
  fabric_version=0.135.0+1.21.10

# Mod Properties
  group=com.minelittlepony
  displayname=Mson
  authors=Sollace
  description=Json-based entity models. Mson.

# Publishing
  minecraft_version_range=>=1.21.10
  modrinth_loader_type=fabric
  modrinth_project_id=POWgsZW2

# Dependencies
  modmenu_version=16.0.0-rc.1
