name: Check on pull request and push
on:
  - pull_request
  - push
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Fetch Tags
        run: git fetch --tags
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Build Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check
