name: Run Gradle on push and pull request
on:
  - pull_request
jobs:
  gradle:
    strategy:
      matrix:
        java-version: [ 16 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version}}
      - name: Build Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check
